version: '3'
services:
  db:
    image: mongo
    restart: always
  redis:
    image: redis:latest
    ports:
      - "6379:6379"  
  app:
    build: .
    image: myapp:latest
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - '80:80'
    depends_on:
      - app   